name: PyQt Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build PyQt App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd src
        pip install pyinstaller
        pip install -r requirements.txt
        cd ..

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile --add-data "src/icons/*;icons" --noconsole --name BeaClip -i src/icons/logo.ico src/main.py

    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --onefile --add-data "src/icons:icons" --noconsole --name BeaClip src/main.py

    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: pyinstaller --onefile --add-data "src/icons:icons" --noconsole --name BeaClip src/main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BeaClip-${{ matrix.os }}
        path: dist/BeaClip*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.exe dist/*.app BeaClip*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}